version: '3'
services:
  db:
    image: mysql:8
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=mysecretpassword
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypassword
    volumes:
      - ./src/migration/base.sql:/docker-entrypoint-initdb.d/base.sql
    networks:
      - my-network
  app:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
    networks:
      - my-network
  redis:  # New Redis service block
    image: redis:6.2.5  # Use a specific version, not "latest"
    ports:
      - 6379:6379  # Expose Redis port on the host
    networks:
      - my-network

networks:
  my-network:

volumes:
  db-data:
